<?php
// vi: filetype=php

function ccsf_participatory_budget_theme($existing, $type, $theme, $path) {
  return array(
    'ccsf_participatory_budget__district_contact' => array(
      'variables' => array(
        'district' => null
      ),
    ),
  );
}

/**
 * Implements hook_user_login().
 */
function ccsf_participatory_budget_user_login(\Drupal\user\UserInterface $account) {
  // Default login destination to the dashboard.
  $current_request = \Drupal::service('request_stack')->getCurrentRequest();
  if (!$current_request->query->get('destination')) {
    $current_request->query->set(
      'destination',
      \Drupal\Core\Url::fromRoute('<front>')->toString()
    );
  }
}
