<?php

use Drupal\Core\Url;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\User\UserInterface;
use Drupal\User\RoleInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemList;
use Drupal\Core\Database\Query\AlterableInterface;

/**
 * Implements hook_ENTITY_TYPE_access() for entity type "user_role".
 *
 * @param \Drupal\User\RoleInterface $role
 *   The role object to check access for.
 *
 * @param string $operation: The operation that is to be performed on $entity.
 *
 * @param \Drupal\Core\Session\AccountInterface $account: The account trying to access the entity.
 */
function administerusersbyrole_user_role_access(RoleInterface $role, $operation, AccountInterface $account) {
  // Allow users without the permission "administer permissions" to view the
  // role names in the /admin/people view.
  if ($operation == 'view') {
    return AccessResult::allowedIfHasPermission($account, 'access users overview');
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_ENTITY_TYPE_access() for entity type "user".
 *
 * @param \Drupal\User\UserInterface $user
 *   The user object to check access for.
 *
 * @param string $operation: The operation that is to be performed on $entity.
 *
 * @param \Drupal\Core\Session\AccountInterface $account: The account trying to access the entity.
 */
function administerusersbyrole_user_access(UserInterface $user, $operation, AccountInterface $account, array $extra_roles = NULL) {
  // Never allow uid 0 (anonymous) or 1 (master admin).
  if (!$user->isNew() && ($user->id() <= 1)) {
    return AccessResult::neutral();
  }

  // Grant access to view blocked users if we can update them.
  if ($user->isBlocked() && ($operation == 'view')) {
    $operation = 'update';
  }

  $roles = $user->getRoles(TRUE);
  if ($extra_roles) {
    $roles = array_unique(array_merge($roles, $extra_roles));
  }

  $result = \Drupal::service('plugin.manager.administerusersbyrole')->get()->access($roles, $operation, $account);
  return $result->cachePerPermissions()->addCacheableDependency($user);
}

/**
 * Implements hook_entity_field_access().
 */
function administerusersbyrole_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemList $items = NULL) {
  if ($field_definition->getTargetEntityTypeId() != 'user') {
    return AccessResult::neutral();
  }

  $fields = array('name', 'status', 'mail', 'roles');
  if ($operation == 'view') {
    $fields[] = 'access';
  }

  if (!in_array($field_definition->getName(), $fields)) {
    return AccessResult::neutral();
  }

  if (is_null($items)) {
    if ($operation == 'view') {
      // No field item list is passed.  This can be used to control whether to hide/show the whole column in views.
      // Hence allow if 'access users overview'.
      return AccessResult::allowedIfHasPermission($account, 'access users overview');
    }
    return AccessResult::neutral();
  }

  $extra_roles = NULL;
  if (($field_definition->getName() == 'roles') && ($operation == 'edit')) {
    $operation = 'role-assign';
    $extra_roles = array_map(function($value) { return $value['target_id']; }, $items->getValue());
  }

  return administerusersbyrole_user_access($items->getEntity(), $operation, $account, $extra_roles);
}

/**
 * Implements hook_query_TAG_alter().
 *
 * Modifies the user listing results to exclude user accounts that the logged
 * in user does not have permission to modify.
 */
function administerusersbyrole_query_administerusersbyrole_edit_access_alter(AlterableInterface $query) {
  $account = \Drupal::currentUser();
  // The tag administerusersbyrole_edit_access is used to indicate that we
  // should filter out users where there isn't edit access.
  if (!$account->hasPermission('administer users')) {
    // Exclude the root user.
    $query->condition('users_field_data.uid', 1, '<>');

    // Hide any user accounts that the user does not have permission to edit.
    // If an account has multiple roles, we make sure the current user has
    // permission to edit all assigned roles.
    $roles = \Drupal::service('plugin.manager.administerusersbyrole')->get()->listRoles('edit', $account);

    // Get a list of uids with roles that the user does not have permission
    // to edit.
    $subquery = \Drupal::database()->select('user__roles', 'ur2');
    $subquery->fields('ur2', array('entity_id'));

    if ($roles) {
      // This code was changed from D7 to workaround D8 core bug https://www.drupal.org/node/2744069.
      $subquery->condition('ur2.roles_target_id', $roles, 'NOT IN');
    }

    // Exclude those uids from the result list.
    $query->condition('users_field_data.uid', $subquery, 'NOT IN');
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Enable roles if required.
 */
function administerusersbyrole_form_user_form_alter(&$form, &$form_state) {
  $user = $form_state->getFormObject()->getEntity();
  $account = Drupal::currentUser();

  if (administerusersbyrole_user_access($user, 'role-assign', $account)->isAllowed()) {
    $allowed = \Drupal::service('plugin.manager.administerusersbyrole')->get()->listRoles('role-assign', $account);
    $options = array_intersect_key($form['account']['roles']['#options'], array_flip($allowed));
    $form['account']['roles']['#options'] = $options;
    $form['account']['roles']['#access'] = !empty($options);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Enable cancel delete if required.
 */
function administerusersbyrole_form_user_cancel_form_alter(&$form, &$form_state) {
  $user = $form_state->getFormObject()->getEntity();
  $account = Drupal::currentUser();

  if (administerusersbyrole_user_access($user, 'delete', $account)->isAllowed()) {
    $form['user_cancel_method']['user_cancel_delete']['#access'] = TRUE;
  }
}

/**
 * Implements hook_help().
 */
function administerusersbyrole_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.administerusersbyrole':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Administer Users by Role allows site builders to set up fine-grained permissions for allowing "sub-admin" users to manage other users based on the target user\'s role.');
      $output .= t('The module defines new permissions to control access to edit/delete users and assign roles - more specific than Drupal Core\'s all-or-nothing \'administer users\' and \'administer permissions\'.');
      $output .= t('It also provides a \'create users\' permission and fine-grained permissions for viewing users.') . '</p>';
      $output .= '<h3>' . t('Configuration') . '</h3>';
      $output .= '<p>' . t('The module supports two modes, depending on <a href=":config">configuration settings</a>.', [':config' => \Drupal::url('administerusersbyrole.settings')]) . '</p>';
      $output .= '<ul>';
      $output .= '<li>' . t('In the default <em>simple</em> mode the admin defines a set of \'safe roles\'.  There is one permission for each operation - view/edit/cancel/assign role - which allows access if the target user\'s roles are all in the set of safe roles.') . '</li>';
      $output .= '<li>' . t('In the <em>complex</em> mode, there is a permission for each operation for each role.  Access for an operation is granted only if the sub-admin has the base permission for the operation plus permission for every role of the target user.') . '</li>';
      $output .= '</ul>';
      $output .= '<h3>' . t('Core permissions') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Administer users') . '/' . t('Administer permissions') . '</dt>';
      $output .= '<dd>' . t('<em>Do not</em> set these for sub-admins.  These permissions bypass all of the permissions in "Administer Users by Role".') . '</dd>';
      $output .= '<dt>' . t('View user profiles') . '</dt>';
      $output .= '<dd>' . t('Don\'t set this if you wish to use the fine-grained permissions for viewing users.') . '</dd>';
      $output .= '</dl>';
      $output .= '<h3>' . t('New permissions') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Access the users overview page') . '</dt>';
      $output .= '<dd>' . t('Grants access to <a href=":people">manage users page</a>. Only users that can be edited are shown.', [':people' => \Drupal::url('entity.user.collection')]) . '</dd>';
      $output .= '<dt>' . t('Create new users') . '</dt>';
      $output .= '<dd>' . t('Grants access to <a href=":create">create users</a>.', [':create' => \Drupal::url('user.admin_create')]) . '</dd>';
      $output .= '<dt>' . t('Assign roles by role') . '</dt>';
      $output .= '<dd>' . t('Allows assigning of roles.  The set of roles than can be assigned is controlled by configuration.') . '</dd>';
      $output .= '<dt>' . t('Edit users by role') . '</dt>';
      $output .= '<dd>' . t('Allows editing of any user that has no roles set.  Editing of users with roles depends on configuration.') . '</dd>';
      $output .= '<dt>' . t('Cancel users by role') . '</dt>';
      $output .= '<dd>' . t('Allows cancelling of any user that has no roles set.  Cancelling of users with roles depends on configuration.') . '</dd>';
      $output .= '<dt>' . t('View users by role') . '</dt>';
      $output .= '<dd>' . t('Allows viewing of any user that has no roles set.  Viewing of users with roles depends on configuration.  Note that this permission only controls direct viewing of a single user, it does not affect Views.') . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}
