settings:
  confirmation_message: 'Se ha enviado su mensaje.'
handlers:
  email_confirmation:
    settings:
      from_name: predeterminado
  email_notification:
    label: 'Aviso por correo electrónico'
