display:
  default:
    display_title: 主
    display_options:
      exposed_form:
        options:
          submit_button: 过滤
          reset_button_label: 重置
          exposed_sorts_label: 排序依据
          sort_asc_label: 升序
          sort_desc_label: 降序
      pager:
        options:
          tags:
            previous: '‹ 上一个'
            next: '下一个 ›'
            first: '« 首页'
            last: '末页 »'
          expose:
            items_per_page_label: 每页条目数
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 偏移量
      fields:
        user_bulk_form:
          label: 批量更新
        name:
          label: 用户名
        status:
          label: 状态
          settings:
            format_custom_true: 有效
            format_custom_false: 阻止
        roles:
          label: 角色
          separator: '， '
        created:
          label: 注册了
        access:
          label: 上次访问
        operations:
          label: 操作
        mail:
          separator: '， '
      filters:
        combine:
          expose:
            label: 名称或电子邮件含有
        roles_target_id:
          expose:
            label: 角色
        permission:
          expose:
            label: 权限
        status:
          group_info:
            label: 状态
            group_items:
              1:
                title: 有效
              2:
                title: 阻止
      title: 人员
      empty:
        area_text_custom:
          content: 没有用户可用。
      use_more_text: 更多
  page_1:
    display_title: 页面
    display_options:
      menu:
        title: 列表
      tab_options:
        title: 人员
        description: 管理用户账号、角色和权限。
