administerusersbyrole.settings:
  type: config_object
  label: 'Administer Users by Role settings'
  mapping:
    mode:
      type: string
      label: 'Mode'
    simple:
      type: mapping
      mapping:
        include_exclude:
          type: string
          label: 'Include or exclude'
        roles:
          type: sequence
          label: 'Roles'
          sequence:
            type: string
            label: 'Role'
