node_type_district_landing_page_status: '1'
node_type_district_landing_page_pattern: 'District [node:field_district:entity:field_district_number] Landing Page'
node_type_district_landing_page_php: 0
submit: 'Save configuration'
form_build_id: form-wrp6QB10qgmQ4X420A-aewBorSr1elNXPC2FGQLfWrA
form_token: wScxzS6e9isYHK5qxRqB2BjGWKa0_F68MecSmyKXe1w
form_id: auto_entitylabel_settings_form
op: 'Save configuration'
node_type_district_voting_page_status: '1'
node_type_district_voting_page_pattern: 'District [node:field_district:entity:field_district_number] Voting Page'
node_type_district_voting_page_php: 0
