module:
  admin_links_access_filter: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  administerusersbyrole: 0
  administerusersbyrole_hack: 0
  auto_entitylabel: 0
  block: 0
  breakpoint: 0
  ccsf_district: 0
  ccsf_participatory_budget: 0
  ckeditor: 0
  config: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  image: 0
  kint: 0
  link: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  system: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  user: 0
  menu_link_content: 1
  pathauto: 1
  minimal: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  seven: 0
  participatory_budget: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
