#!/bin/bash

# Go to base level of project
cd "$(dirname $0)/../../"

# Exit immediately on errors, and echo commands as they are executed.
set -ex

# Set the $PATH to include the global composer bin directory.
PATH=$PATH:~/.composer/vendor/bin

cd tests && ../vendor/bin/behat --config=behat.yml --profile local "$@"
